### ISSUE TITLE
Analyzing the bad ducc0 interactions on Cineca

### ISSUE THREAD

**Issue by mreineck** [litebird/litebird_sim#384]
I'm opening this to document the efforts of tracking down the mysterious interactions between `ducc0>=0.35` and MPI on Cineca (see also https://github.com/litebird/litebird_sim/pull/383).

What I would like to do first is try and get the `ducc0` compilation from source to work on the machine, since it will help tremendously with debugging.

@ziotom78, @paganol, could you please send me the full output of
```
<load most up-to-date modules for Python and gcc>
VERBOSE= pip3 install --no-binary ducc0 -v ducc0
```
?
The build script should take care of downloading all dependencies (currently `pybind11` and `nanobind`, but only `pybind11` is currently used).

**Comment by paganol** [comment]
Hi @mreineck,

I tried this

```
module load gcc/12.2.0 openmpi/4.1.6--gcc--12.2.0
conda create -n test_ducc0 python=3.11
conda activate test_ducc0
VERBOSE= pip3 install --no-binary ducc0 -v ducc0
```

here the output 
[output.log](https://github.com/user-attachments/files/20023713/output.log)

**Comment by mreineck** [comment]
Thank you! So the installation from source does work for 0.37.1, if I'm reading this right, correct? @ziotom78 mentioned that this didn't work for him, but probably that was for the 0.34/0.35 releases, which were still based on `setuptools`.

My hope is that this self-compiled version might already work with `litebird-sim`. If not, I have a handful of ideas what I could patch, but it's mostly guesswork.

**Comment by ziotom78** [comment]
> Thank you! So the installation from source does work for 0.37.1, if I'm reading this right, correct? [@ziotom78](https://github.com/ziotom78) mentioned that this didn't work for him, but probably that was for the 0.34/0.35 releases, which were still based on `setuptools`.
> 
> My hope is that this self-compiled version might already work with `litebird-sim`. If not, I have a handful of ideas what I could patch, but it's mostly guesswork.

Hi Martin, I did not try the command `pip3 install …` but instead cloned the ducc0 repository and tried to compile it manually using `cmake`. (My attempt failed because CMake found no `pybind11` available.)

If you could tell me the shortest way to compile the Python library from the source and install it in the current virtual environment, I could use `git bisect` to find the commit causing the problem with LBS.

**Comment by ziotom78** [comment]
To be precise, I activated a local virtual environment and installed `pybind11` and `nanobind` with the following command:

    pip install pybind11 nanobind

But CMake complains it cannot find `pybind11`:

```
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Debug ..
CMake Error at CMakeLists.txt:42 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by mreineck** [comment]
Ah, sorry @ziotom78, that was a misunderstanding!
In 0.35, a `CMakeLists.txt` file appeared in the repository, but that was an external contribution with the goal to make C++-only compilation easier.
Later in 0.37 I switched from `pyproject.toml + setup.py` to a `pyproject.toml + CMakeLists.txt` build approach. So `CMakeLists.txt` was changed to support Python compilation, but it is meant to be called only via `pip`; I have no idea whether it can be made to work in a standalone fashion.
So in principle, all `ducc` versions should support compilation from source from a repo clone, via
`pip install .`
or similar. All required dependencies will be installed automatically.

**Comment by ziotom78** [comment]
Thank you so much Martin, I was finally able to compile Ducc and test it against LBS @ CINECA!

Using `git bisect`, I found that the very first commit showing this problem is `dc47ef7a2a428ea1a9bb6b50493c447c399c3d79` (*make PointingProvider use quaternions in a periodic fashion*), made on Saturday May, 4th 2024. It is just 44 lines of code in `python/pointingprovider_pymod.cc`, so it seems your guess was correct.

**Comment by mreineck** [comment]
Wow, thank you for doing this analysis!
This makes me optimistic that we can fix the problem in some way, even if it should be a compiler bug, by reformulating the code in question. Let's see!

**Comment by mreineck** [comment]
OK, there was indeed a bug in the `PointingProvider` class ... this should now be fixed, but I don't understand how it could have caused the symptoms you saw in `litebird_sim` (it wasn't a memory corruption issue). But fingers crossed, hopefully the current `ducc0` `HEAD` works now nevertheless!

**Comment by ziotom78** [comment]
> OK, there was indeed a bug in the `PointingProvider` class ... this should now be fixed, but I don't understand how it could have caused the symptoms you saw in `litebird_sim` (it wasn't a memory corruption issue). But fingers crossed, hopefully the current `ducc0` `HEAD` works now nevertheless!

I tested LBS with the latest commit in `ducc0`, and I confirm that the bug has disappeared! 🥳

However, the fact that the problem was not memory-related makes me think that perhaps `ducc0` returned weird quaternions that triggered some unlikely code path in LBS triggering the actual error. If this is the case, the real bug is hidden somewhere else, most likely in some low-level library used by LBS (NumPy, Numba, …), but then the bug would be tough to find.

Thanks a lot for having worked on Sunday, Martin! Once a new version of `ducc0` is available on PyPI, we can update the dependency.

**Comment by mreineck** [comment]
Perfect, that was great teamwork!
I can make a new release available whenever it is useful from LBS's point of view; please let me know!
Otherwise Iplan to release 0.38 in a month or so.

In any case I'd recommend to switch the installation mode for `ducc` in LBS to compilation from source - it should make SHTs and the Mueller convolver roughly twice as fast as they are now.

**Comment by mreineck** [comment]
I thought about the release plans some more ... @ziotom78 do you think it would be good to have a `ducc0` release ready for the hackathon in two weeks? If (as I assume) the code gets some good testing there, it may as well be the most recent version, right?

**Comment by ziotom78** [comment]
I have to reopen this issue because it is not completely solved. Luca discovered that installing `litebird_sim` from scratch on Cineca with the new dependency on `ducc` 0.37.1 still exposes the problem.

However, I did more tests and found that the bug is indeed solved if one compiles `ducc` natively on CINECA. The problem appears only if one uses the default binary wheel. Here are the results; consider that the expected outcome is `unseen_pixels=0` and `unseen_fraction=0.0`:

```
Ducc 2f918f9a (2024-04-16 09:43:01): unseen_pixels=0 / total_pixels=196608 = unseen_fraction=0.0 ✅ 
Ducc 7f8c1974 (2025-03-14 18:10:44): unseen_pixels=98862 / total_pixels=196608 = unseen_fraction=0.50 ❌ 
Ducc cbee1686 (2025-05-04 13:37:45): unseen_pixels=0 / total_pixels=196608 = unseen_fraction=0.0 ✅ 
Ducc e15683e7 (2025-05-16 11:50:41): unseen_pixels=0 / total_pixels=196608 = unseen_fraction=0.0 ✅ 

Ducc 0.34.0 binary wheel: unseen_pixels=98862 / total_pixels=196608 = unseen_fraction=0.50 ✅ 
Ducc 0.37.1 binary wheel: unseen_pixels=98862 / total_pixels=196608 = unseen_fraction=0.50 ❌ 
```

**Comment by mreineck** [comment]
Just to be sure: 0.37.1 still contains the bug in `pointingprovider` that I mentioned above. It's only fixed on the HEAD of the `ducc0` branch. 
To be on the safe side, I'll release 0.38 on Monday. But it's still very curious that manually compiled and wheel versions of 0.37.1 behave differently...

**Comment by mreineck** [comment]
OK, release 0.38.0 should now be accessible! I hope this fixes all the issues :-)

**Comment by paganol** [comment]
It does. Thanks @mreineck!! 🙏

**Comment by mreineck** [comment]
Great! So let's close this for now.
